apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-app
  labels:
    app: devops-test-app
spec:
  selector:
    matchLabels:
        app: devops-test-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-test-app
    spec:
      containers:
        - name: devops-test-app
          image: #{AWS_ACCOUNT_ID}#.dkr.ecr.#{$AWS_DEFAULT_REGION}#.amazonaws.com/#{CONTAINER_IMAGE}#
          ports:
            - containerPort: 5000
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred 