apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ECR_REPOSITORY}
  labels:
    app: ${ECR_REPOSITORY}
spec:
  selector:
    matchLabels:
        app: ${ECR_REPOSITORY}
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${ECR_REPOSITORY}
    spec:
      containers:
        - name: ${ECR_REPOSITORY}
          image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always