apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-app
  labels:
    app: devops-test-app
spec:
  selector:
    matchLabels:
        app: devops-test-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-test-app
    spec:
      containers:
        - name: devops-test-app
          image: public.ecr.aws/l7h9i5e2/devops-test-app/#{CONTAINER_IMAGE}#
          ports:
            - containerPort: 5000
              protocol: TCP
          imagePullPolicy: Always
